### ISSUE TITLE
cases where image is the same in over 500 POI, indicating that it is likely not POI-specific

### ISSUE THREAD

**Issue by matkoniecz** [alltheplaces/alltheplaces#10630]
* [x] image = https://dynl.mktgcdn.com/p/irgrRvtNhff6VLubiBfb0wXj66qCmjjWiKJVpjROaBo/150x150.jpg repeated 1242 times in dominos_pizza_gb - #10636
* [x] image = https://locations.where2getit.com/burlington/images/new/burlington-details.png repeated 1051 times in burlington_us - #10637
* [x] image = https://dynl.mktgcdn.com/p/Xpsc0X8Cq9USpnm7wTmDJ_M35gUtEcLmbBLPvbG64Ow/150x150.png repeated 535 times in lloyds_bank_gb - #10638
* [x] image = https://dynl.mktgcdn.com/p/uxHL7a0wO7r4iSgAuE2vhyByMTOlCWfCVHAERn-dMvw/130x130.jpg repeated 912 times in cato_us - #10639
* [x] image = https://locations.baskinrobbins.com/assets/static/capuccino-734598ab.png repeated 2254 times in baskin_robbins_us - #10640
* [x] image = https://dynl.mktgcdn.com/p/9O2CaFxE9nSCJG5e6r_FzhP0e0iwFOGR4buJNurj6_U/196x196.jpg repeated 637 times in starbucks_ae_sa - #10421
* [x] image = https://stores.foodlion.com/permanent-b0b701/assets/images/hero-fallback.3d0b8665.png repeated 1174 times in food_lion_us - #10641
* [x] image = https://dynl.mktgcdn.com/p/jg5VT7EeUyd3r6YE5DfclNLire8luIpyK0dDmhYRqJc/500x500.png repeated 605 times in nationwide_gb - #10642
* [x] image = https://dynl.mktgcdn.com/p/fPO9PXHOSN4jz92IZcCOEP63GHd-ufYx7YzjGhJiXUU/150x150.jpg repeated 667 times in albertsons - #10643
* [x] image = https://assets.rbl.ms/25637742/origin.jpg repeated 2500 times in penske - #10644
* [x] image = https://www.ameriprise.com/binaries/content/gallery/ampcom/ameriprise-social-image.png repeated 1175 times in ameriprise_us - #10645
* [x] image = https://dynl.mktgcdn.com/p/x09r9louvg69_KeYHPnS2M0C8liZgK2TVvn8GDn7uR8/196x196.jpg repeated 1321 times in big_lots - #10646
* [x] image = https://www.bhf.org.uk/-/media/images/social/facebook-share-image_v5-1.png?rev=63f70ab8b3b148edaef074404a4874c1 repeated 658 times in bhf_gb - #10647
* [x] image = https://rstatic.levi.com/locations/1_7029_levis-banner.png repeated 985 times in levis - #10648
* [x] image = https://rstatic.stores.bealls.com/locations/1459_893_bealls_store_front.jpg repeated 515 times in bealls_us - #10649
* [x] image = https://locations.papajohns.com/assets/static/ogImage-PQRQWxIY.webp repeated 3345 times in papa_johns - #10650
* [x] image = https://www.mercy.com/ repeated 807 times in mercy_health_us - #10651
* [x] image = http://www.coop.co.uk/funeralcare/funeral-directors/static/images/content/fnc_schema_image.jpg repeated 801 times in the_cooperative_group - #10652
* [x] image = https://dynl.mktgcdn.com/p/Ex6BZ7PegozPldmWvTAsXiuX4zM9mzD8jjVUgMdAYxI/150x150.png repeated 1365 times in petco - #10653
* [x] image = https://cdn.thumbor.leadformance.com/media/clients/5c360bbd772d089b709a3baa/c7a985ef-321a-455c-959e-43f9f6f6f5d9-picard-2.jpeg repeated 1175 times in picard_fr - #10654
* [x] image = https://dynl.mktgcdn.com/p/3icSWYKt3qA3GkcrQ38pMZRFYnVTZ3z6km2bYE_cqAI/150x150.png repeated 848 times in american_eagle_outfitters - #10655
* [x] image = https://locations.theupsstore.com/assets/static/storefront_fallback-Bc2t9pGt.svg repeated 3231 times in ups_store - #10656
* [x] image = https://dynl.mktgcdn.com/p/quAyYRFPsjuPE8H_gbrdDiiPS8kdMU8Hm3oEUX1-chI/1440x360.jpg repeated 621 times in moes_southwest_grill - #10657
* [x] image = https://dynl.mktgcdn.com/p/tP30BwCjyRNRQYDzUZ4POPkkpilti-u7QO1Rn1Ozqp8/150x150.jpg repeated 593 times in aldi_sud_au - #10658
* [x] image = https://res.cloudinary.com/cloudasset/image/upload/v1699388694/map/images/wkvygexq0az9oz125oof.jpg repeated 690 times in rainbow_shops - #10659
* [x] image = https://static.nike.com/a/images/f_auto/2e8d9338-b43d-4ef5-96e1-7fdcfd838f8e/image.jpg repeated 992 times in nike - #10660
* [x] image = https://dynl.mktgcdn.com/p/0kiNDvmfMqhh1or-XCUjkCfJEVmp3I5y94NWjBaZNZc/1.0000/150x150.png repeated 1010 times in massage_envy - #10661
* [x] image = https://dynl.mktgcdn.com/p/Ze6KDp_49oDhLP_9GtJ1FeBU1Q-Oy3yQDqN9SkJ5zmo/1440x360.jpg repeated 615 times in jamba_juice - #10662
* [x] image = https://dynl.mktgcdn.com/p/VNkahEa7sRSHyLyMlAx139ar5dy990ORB7RJjweKGQs/196x196.jpg repeated 1451 times in mt_bank_us - #10663
* [x] image = https://dynl.mktgcdn.com/p/Kn3CXLUU0Y42B1cVXheVeutFSdzNaL4avfV0YQAMFdM/196x196.png repeated 600 times in salon_centric_us - #10664
* [x] image = https://dynl.mktgcdn.com/p/oOWgAcHIvnx6ijuwPmyZIkUVJoHIEvFyzbBmbAqdwYk/150x150.png repeated 4999 times in jackson_hewitt - #10665
* [x] image = https://dynl.mktgcdn.com/p/ugVeu_I7n9ph4B3cT6SZ6fyDoG9DxqRIS0jD53oN5w8/800x800.png repeated 5860 times in wendys - #10666
* [x] image = https://dynl.mktgcdn.com/p/i42wHLnWtTr8H6IbjnNLIgc-mw6GWlg0qRfPm4dM2lk/150x150.png repeated 866 times in maurices - #10667
* [x] image = https://dynl.mktgcdn.com/p/fKrePdCdx2ELmLmLAhZS4wmMUa0gBGvpkk-lqPcPASc/150x150.jpg repeated 1077 times in fifth_third_bank - #10668
* [x] image = https://netto-pl-prod.imgix.net/media/1001/dsc07822.jpg?rect=240%2C0%2C1120%2C600&w=1120&h=600&s=8da5979abde055402cf0d2339eaaf000 repeated 667 times in netto_salling - #10669
* [x] image = https://dynl.mktgcdn.com/p/eSOZdhuokAtI3xavHfSTfgUG57lTEwCKQfYiNNFL-PA/2697x2697.png repeated 653 times in bojangles - #10670
* [x] image = https://agences.sg.fr/banque-assurance/UI/20240628-105709/photos/agence/agence-sg.jpg repeated 1452 times in societe_generale - #10671
* [x] image = https://dynl.mktgcdn.com/p/vfVdaxyP_jDZdsuJUp6zjXXz7jkJ87XeGPMuAnvDNYU/150x150.png repeated 1067 times in papa_murphys - #10672
* [x] image = https://dynl.mktgcdn.com/p/aT0JcVtNProJLhR2fnA6l9nUx_qyHFJzDBo90WITFZk/1440x360.jpg repeated 1315 times in auntie_annes - #10673
* [x] image = https://dynl.mktgcdn.com/p/nTcyfpfO8CZssVSdufETsSE5_Entw6NuYztIPH7kwl8/150x150.jpg repeated 2160 times in gnc - #10674
* [x] image = https://dynl.mktgcdn.com/p/nrW7uT2LniB-3ozNvXSk-7YzpnRswiIJF2aKkB7WlA4/150x150.png repeated 2214 times in subway - #10675
* [x] image = https://a.mktgcdn.com/p/WgP1HqrBbp6ZN6CEhQ9eBVArXryRomz_GbViOR2MnFo/1000x1000.png repeated 1422 times in costcutter_gb - #10676
* [x] image = https://a.mktgcdn.com/p/nPXC-M1VA3qVTlC6qjkDiAY-hVyrKROJ38JAwPjSwNw/378x378.png repeated 561 times in bestone_gb - #10677
* [x] image = https://images.vans.com/is/content/VansBrand/english/panels/customs/HO20/ho20_simpsons_homepage-secondarybanner.gif repeated 710 times in vans - #10678

Maybe `image` or `phone` that is repeated over 10 times should be thrown out automatically? Without throwing it out manually by changing spider?

Note that in case where former logos are replaced by actual images they would not continue to be thrown out.

**Comment by matkoniecz** [comment]
continuation in #10679
